# Generated by Django 4.0.6 on 2022-07-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddatabase', '0002_rename_food_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
